version: '3.8'

services:

  nodejs:
    container_name: products_nodejs
    image: alperyesilyurt/nodejs_productapi
    ports:
      - "3001:3000"
    depends_on:
      - mongodb
    environment:
      DB_CON_STR: mongodb://my_mongodb:27017/farmStand

  mongodb:
    image: mongo
    container_name: my_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    
volumes:
  mongodb_data:
